-- CreateTable
CREATE TABLE "customers" (
    "id" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "lastVisit" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'Ativo',
    "code" TEXT,
    "name" TEXT NOT NULL,
    "tradeName" TEXT,
    "type" TEXT,
    "cnpj" TEXT NOT NULL,
    "stateRegistration" TEXT,
    "ieIndicator" TEXT,
    "originCode" TEXT,
    "origin" TEXT,
    "mainContact" TEXT,
    "email" TEXT,
    "phone" TEXT,
    "commercialPhone" TEXT,
    "mobile" TEXT,
    "whatsapp" TEXT,
    "allowWhatsapp" BOOLEAN NOT NULL DEFAULT false,
    "allowEmail" BOOLEAN NOT NULL DEFAULT false,
    "allowSMS" BOOLEAN NOT NULL DEFAULT false,
    "allowPhone" BOOLEAN NOT NULL DEFAULT false,
    "zipCode" TEXT,
    "street" TEXT,
    "number" TEXT,
    "complement" TEXT,
    "neighborhood" TEXT,
    "city" TEXT,
    "state" TEXT,
    "cityCode" TEXT,
    "country" TEXT,
    "occupationCode" TEXT,
    "occupation" TEXT,
    "discountPercentage" DOUBLE PRECISION,
    "paymentMethod" TEXT,
    "paymentCondition" TEXT,
    "clientType" TEXT,
    "clientTypeDescription" TEXT,
    "observations" TEXT,

    CONSTRAINT "customers_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "customers_cnpj_key" ON "customers"("cnpj");